config:
  debugEnabled: true
  adminEnabled: true
  metricsEnabled: true
  preInit: false

  organizationName: "Student"
  organizationKey: "0xf9d07b8332359de8e37ed654b0b5211c008cf22f"
  fireflyContractAddress: "/instances/0x17a3a4d50f05603d8593a71bd79d853c03cede79"

  ethconnectUsername: "u0he1sww0t"
  ethconnectPassword: "lZY3PRnXJTfw59xEzYqxfG0SzKfBYV0Dsr17RLLelYM"
  ethconnectUrl: "https://u0g0yrqy4r-u0xm0vhxib-connect.us0-aws.kaleido.io"

  postgresUrl: "postgres://postgres:firef1y@postgresql.default.svc:5432?sslmode=disable"
  postgresAutomigrate: true

  ipfsGatewayUsername: "u0he1sww0t"
  ipfsGatewayPassword: "lZY3PRnXJTfw59xEzYqxfG0SzKfBYV0Dsr17RLLelYM"
  ipfsApiUsername: "u0he1sww0t"
  ipfsApiPassword: "lZY3PRnXJTfw59xEzYqxfG0SzKfBYV0Dsr17RLLelYM"
  ipfsApiUrl: "https://u0g0yrqy4r-u0eojoyk7y-ipfs.us0-aws.kaleido.io"
  ipfsGatewayUrl: "https://u0g0yrqy4r-u0eojoyk7y-ipfs.us0-aws.kaleido.io"


core:
  metrics:
    serviceMonitor:
      enabled: true
  jobs:
    registration:
      enabled: true

dataexchange:
  tlsSecret:
    enabled: false
  certificate:
    enabled: true
    issuerRef:
      name: selfsigned-ca
      kind: ClusterIssuer