config:
  debugEnabled: true
  adminEnabled: true
  metricsEnabled: true
  preInit: true

  organizationName: "firefly-os"
  organizationKey: "0xeb7284ce905e0665b7d42cabe31c76c45da1d331"
  fireflyContractAddress: "0xeb7284ce905e0665b7d42cabe31c76c45da1d254"

  ethconnectUrl: "http://ethconnect.firefly-os"

  ipfsApiUrl: "http://ipfs.firefly-os:5001"
  ipfsGatewayUrl: "http://ipfs.firefly-os:8080"

  databaseOverride: |-
    type: postgres
    postgres:
      migrations:
        auto: false

core:
  extraEnv:
    - name: FIREFLY_DATABASE_POSTGRES_URL
      valueFrom:
        secretKeyRef:
          name: custom-psql-config
          key: url
  jobs:
    postgresMigrations:
      enabled: true
      extraEnv:
        - name: PSQL_URL
          valueFrom:
            secretKeyRef:
              name: custom-psql-config
              key: url

  metrics:
    serviceMonitor:
      enabled: true

dataexchange:
  certificate:
    enabled: true
    issuerRef:
      kind: ClusterIssuer
      name: selfsigned-ca

  tlsSecret:
    enabled: false


# dataexchange:
#   certificate:
#     enabled: true
#     issuerRef:
#       kind: ClusterIssuer
#       name: selfsigned-ca

#   tlsSecret:
#     enabled: false

# config:
#   debugEnabled: true
#   adminEnabled: true
#   metricsEnabled: true
#   preInit: true

#   organizationName: "Org 1"
#   organizationKey: "0xf9d07b8332359de8e37ed654b0b5211c008cf22f"
#   fireflyContractAddress: "instances/0xdf31679a0e53069a8aa007f94fadc4a7d47b5593"

#   ethconnectUrl: "https://u0g0yrqy4r-u0xm0vhxib-connect.us0-aws.kaleido.io"

#   ipfsApiUrl: "https://u0g0yrqy4r-u0eojoyk7y-ipfs.us0-aws.kaleido.io"
#   ipfsGatewayUrl: "https://u0g0yrqy4r-u0eojoyk7y-ipfs.us0-aws.kaleido.io"

#   databaseOverride: |-
#     type: postgres
#     postgres:
#       migrations:
#         auto: false

# core:
#   extraEnv:
#     - name: FIREFLY_DATABASE_POSTGRES_URL
#       valueFrom:
#         secretKeyRef:
#           name: custom-psql-config
#           key: url
#   jobs:
#     postgresMigrations:
#       enabled: true
#       extraEnv:
#         - name: PSQL_URL
#           valueFrom:
#             secretKeyRef:
#               name: custom-psql-config
#               key: url

#   metrics:
#     serviceMonitor:
#       enabled: true

# dataexchange:
#   certificate:
#     enabled: true
#     issuerRef:
#       kind: ClusterIssuer
#       name: selfsigned-ca

#   tlsSecret:
#     enabled: false
